// <auto-generated />
using AlphaLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlphaLab.Data.Migrations
{
    [DbContext(typeof(AlphaLabDbContext))]
    [Migration("20260716010710_DataQualityFlags")]
    partial class DataQualityFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AlphaLab.Data.Entities.ApiUsageLogRow", b =>
                {
                    b.Property<string>("AsOf")
                        .HasColumnType("TEXT")
                        .HasColumnName("as_of");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<int>("Calls")
                        .HasColumnType("INTEGER")
                        .HasColumnName("calls");

                    b.Property<int?>("PlanLimit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plan_limit");

                    b.HasKey("AsOf", "Source");

                    b.ToTable("api_usage_log", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.BarRow", b =>
                {
                    b.Property<long>("SecurityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("security_id");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<double?>("AdjClose")
                        .HasColumnType("REAL")
                        .HasColumnName("adj_close");

                    b.Property<double?>("AdjHigh")
                        .HasColumnType("REAL")
                        .HasColumnName("adj_high");

                    b.Property<double?>("AdjLow")
                        .HasColumnType("REAL")
                        .HasColumnName("adj_low");

                    b.Property<double?>("AdjOpen")
                        .HasColumnType("REAL")
                        .HasColumnName("adj_open");

                    b.Property<double?>("Close")
                        .HasColumnType("REAL")
                        .HasColumnName("close");

                    b.Property<double?>("High")
                        .HasColumnType("REAL")
                        .HasColumnName("high");

                    b.Property<double?>("Low")
                        .HasColumnType("REAL")
                        .HasColumnName("low");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("observed_at");

                    b.Property<double?>("Open")
                        .HasColumnType("REAL")
                        .HasColumnName("open");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("eodhd")
                        .HasColumnName("source");

                    b.Property<long?>("Volume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume");

                    b.HasKey("SecurityId", "Date", "Version");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("ix_bars_observed");

                    b.ToTable("bars", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.CatchupLogRow", b =>
                {
                    b.Property<string>("AsOf")
                        .HasColumnType("TEXT")
                        .HasColumnName("as_of");

                    b.Property<string>("RecoveredAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recovered_at");

                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.HasKey("AsOf");

                    b.ToTable("catchup_log", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.ConfigRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("ChangedOn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_on");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_json");

                    b.HasKey("Key", "Version");

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.CorporateActionRow", b =>
                {
                    b.Property<long>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("action_id");

                    b.Property<decimal?>("CashPerShare")
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_per_share");

                    b.Property<long?>("CounterpartySecurityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("counterparty_security_id");

                    b.Property<string>("EffectiveDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_date");

                    b.Property<string>("ExDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ex_date");

                    b.Property<string>("NewSymbol")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_symbol");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("observed_at");

                    b.Property<string>("ProcessedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_on");

                    b.Property<double?>("Ratio")
                        .HasColumnType("REAL")
                        .HasColumnName("ratio");

                    b.Property<long>("SecurityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("security_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("eodhd")
                        .HasColumnName("source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("ActionId");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("ix_corporate_actions_observed");

                    b.HasIndex("SecurityId", "Type", "EffectiveDate", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_corporate_actions_identity");

                    b.ToTable("corporate_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_corporate_actions_type", "type IN ('dividend','split','ticker_change','merger_cash','merger_stock','merger_mixed','spinoff','delist')");
                        });
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.DataQualityFlagRow", b =>
                {
                    b.Property<long>("FlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("flag_id");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("issue");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("observed_at");

                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.Property<long?>("SecurityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("security_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("FlagId");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_data_quality_flags_run");

                    b.ToTable("data_quality_flags", null, t =>
                        {
                            t.HasCheckConstraint("ck_data_quality_flags_issue", "issue IN ('missing_bar','nan_field','non_positive_price','outlier_return','unexplained_adjustment','cross_check_mismatch')");

                            t.HasCheckConstraint("ck_data_quality_flags_severity", "severity IN ('warn','reject')");
                        });
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.IndexMembershipLogRow", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("log_id");

                    b.Property<string>("AddsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("adds_json");

                    b.Property<int>("Agreed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agreed");

                    b.Property<string>("AsOf")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("as_of");

                    b.Property<int?>("CrosscheckCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("crosscheck_count");

                    b.Property<string>("DropsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("drops_json");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int?>("SourceCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_count");

                    b.HasKey("LogId");

                    b.ToTable("index_membership_log", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.IndexMembershipRow", b =>
                {
                    b.Property<long>("SecurityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("security_id");

                    b.Property<string>("AddedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_on");

                    b.Property<string>("RemovedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("removed_on");

                    b.HasKey("SecurityId", "AddedOn");

                    b.ToTable("index_membership", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.JobRow", b =>
                {
                    b.Property<long>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_id");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_json");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_json");

                    b.Property<string>("ResultRef")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_ref");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("submitted_at");

                    b.HasKey("JobId");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_kind", "kind IN ('replay','analysis_brief','analysis_skeptic')");

                            t.HasCheckConstraint("ck_jobs_status", "status IN ('queued','running','done','failed')");
                        });
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.RunRow", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.Property<string>("AsOf")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("as_of");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("InputsHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("inputs_hash");

                    b.Property<string>("RunKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_kind");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("running")
                        .HasColumnName("status");

                    b.Property<string>("Watermark")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("watermark");

                    b.HasKey("RunId");

                    b.ToTable("runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_runs_run_kind", "run_kind IN ('live','catchup','replay')");
                        });
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.SectorChangeRow", b =>
                {
                    b.Property<long>("SecurityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("security_id");

                    b.Property<string>("ChangedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_on");

                    b.Property<string>("NewIndustry")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_industry");

                    b.Property<string>("NewSector")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_sector");

                    b.Property<string>("OldIndustry")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_industry");

                    b.Property<string>("OldSector")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_sector");

                    b.HasKey("SecurityId", "ChangedOn");

                    b.ToTable("sector_changes", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.SecurityRow", b =>
                {
                    b.Property<long>("SecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("security_id");

                    b.Property<string>("CurrentSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("current_symbol");

                    b.Property<string>("DelistedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("delisted_on");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT")
                        .HasColumnName("exchange");

                    b.Property<string>("FirstSeen")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen");

                    b.Property<string>("Industry")
                        .HasColumnType("TEXT")
                        .HasColumnName("industry");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Sector")
                        .HasColumnType("TEXT")
                        .HasColumnName("sector");

                    b.HasKey("SecurityId");

                    b.HasIndex("CurrentSymbol", "Exchange")
                        .IsUnique()
                        .HasDatabaseName("ux_securities_active_symbol")
                        .HasFilter("delisted_on IS NULL");

                    b.ToTable("securities", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.TickerHistoryRow", b =>
                {
                    b.Property<long>("SecurityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("security_id");

                    b.Property<string>("ValidFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("valid_from");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<string>("ValidTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("valid_to");

                    b.HasKey("SecurityId", "ValidFrom");

                    b.HasIndex("Symbol", "ValidFrom")
                        .HasDatabaseName("ix_ticker_hist_symbol");

                    b.ToTable("ticker_history", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.TradingCalendarRow", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("CloseTimeLocal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("close_time_local");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session");

                    b.HasKey("Date");

                    b.ToTable("trading_calendar", null, t =>
                        {
                            t.HasCheckConstraint("ck_trading_calendar_session", "session IN ('full','half')");
                        });
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.WorkerStateRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("CurrentRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_run_id");

                    b.Property<string>("HeartbeatAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("heartbeat_at");

                    b.Property<int>("RunInProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("run_in_progress");

                    b.HasKey("Id");

                    b.ToTable("worker_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_worker_state_id", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RunInProgress = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
