// <auto-generated />
using AlphaLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlphaLab.Data.Migrations
{
    [DbContext(typeof(AlphaLabDbContext))]
    partial class AlphaLabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AlphaLab.Data.Entities.CatchupLogRow", b =>
                {
                    b.Property<string>("AsOf")
                        .HasColumnType("TEXT")
                        .HasColumnName("as_of");

                    b.Property<string>("RecoveredAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recovered_at");

                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.HasKey("AsOf");

                    b.ToTable("catchup_log", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.ConfigRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("ChangedOn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_on");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_json");

                    b.HasKey("Key", "Version");

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.JobRow", b =>
                {
                    b.Property<long>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_id");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_json");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_json");

                    b.Property<string>("ResultRef")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_ref");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("submitted_at");

                    b.HasKey("JobId");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_kind", "kind IN ('replay','analysis_brief','analysis_skeptic')");

                            t.HasCheckConstraint("ck_jobs_status", "status IN ('queued','running','done','failed')");
                        });
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.RunRow", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.Property<string>("AsOf")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("as_of");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("InputsHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("inputs_hash");

                    b.Property<string>("RunKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_kind");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("running")
                        .HasColumnName("status");

                    b.Property<string>("Watermark")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("watermark");

                    b.HasKey("RunId");

                    b.ToTable("runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_runs_run_kind", "run_kind IN ('live','catchup','replay')");
                        });
                });

            modelBuilder.Entity("AlphaLab.Data.Entities.WorkerStateRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("CurrentRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_run_id");

                    b.Property<string>("HeartbeatAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("heartbeat_at");

                    b.Property<int>("RunInProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("run_in_progress");

                    b.HasKey("Id");

                    b.ToTable("worker_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_worker_state_id", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RunInProgress = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
